<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="myntra-MacBookPro" name="ATSServiceTest" tests="10" failures="10" timestamp="17 May 2018 10:12:49 GMT" time="1.443" errors="0">
  <testcase name="testAddressScoreAPIValidatation" time="1.274" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
  <testcase name="testAddressScoreAPIValidatation" time="0.006" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
  <testcase name="testAddressScoreAPIValidatation" time="0.006" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
  <testcase name="testAddressScoreAPIValidatation" time="0.006" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
  <testcase name="testAddressScoreAPIValidatation" time="0.004" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
  <testcase name="testAddressScoreAPIValidatation" time="0.008" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
  <testcase name="testAddressScoreAPIValidatation" time="0.006" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
  <testcase name="testAddressScoreAPIValidatation" time="0.005" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
  <testcase name="testAddressScoreAPIValidatation" time="0.009" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
  <testcase name="testAddressScoreAPIValidatation" time="0.006" classname="com.myntra.apiTests.portalservices.atsService.TestATSAPISV2">
    <failure type="java.lang.RuntimeException" message="Error calling Put request ">
      <![CDATA[java.lang.RuntimeException: Error calling Put request 
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:491)
	at com.myntra.test.commons.service.HttpExecutorService.executeHttpService(HttpExecutorService.java:49)
	at com.myntra.apiTests.portalservices.atsService.ATSHelperV2.getATSAddresscore(ATSHelperV2.java:102)
	at com.myntra.apiTests.portalservices.atsService.TestATSAPISV2.testAddressScoreAPIValidatation(TestATSAPISV2.java:33)
Caused by: java.net.UnknownHostException: ats.mjint.myntra.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.myntra.test.commons.service.impl.BaseSvcImpl.put(BaseSvcImpl.java:476)
	... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddressScoreAPIValidatation -->
</testsuite> <!-- ATSServiceTest -->
